### ISSUE TITLE
empty mesh

### ISSUE THREAD

**Issue by vietpho** [hugoycj/Instant-angelo#19]
Hi,

I wanted to try your amazing work, but I'm encountering some issues.

---------------------------------------------
Traceback (most recent call last):
  File "launch.py", line 127, in <module>
    main()
  File "launch.py", line 117, in main
    trainer.test(system, datamodule=dm)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 794, in test
    return call._call_and_handle_interrupt(
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 842, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1188, in _run_stage
    return self._run_evaluate()
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1228, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\loops\loop.py", line 206, in run
    output = self.on_run_end()
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\work\Proj_0_candidates\Instant-angelo\systems\neus.py", line 303, in test_epoch_end
    self.export()
  File "C:\work\Proj_0_candidates\Instant-angelo\systems\neus.py", line 306, in export
    mesh = self.model.export(self.config.export)
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\work\Proj_0_candidates\Instant-angelo\models\neus.py", line 311, in export
    mesh = self.isosurface()
  File "C:\work\Proj_0_candidates\Instant-angelo\models\neus.py", line 114, in isosurface
    mesh = self.geometry.isosurface()
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\work\Proj_0_candidates\Instant-angelo\models\geometry.py", line 109, in isosurface
    vmin, vmax = mesh_coarse['v_pos'].amin(dim=0), mesh_coarse['v_pos'].amax(dim=0)
**IndexError: amin(): Expected reduction dim 0 to have non-zero size.**
Traceback (most recent call last):
  File "C:\work\Proj_0_candidates\Instant-angelo\run_neural_python_colmap_sparse.py", line 25, in <module>
    subprocess.run([
  File "C:\Users\hyun\anaconda3\envs\cu118\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'launch.py', '--config', 'configs/neuralangelo-colmap_sparse.yaml', '--gpu', '0', '--train', 'dataset.root_dir=D:/Projects/geomvs_tmp/b1_iangelo']' returned non-zero exit status 1.

Process finished with exit code 1

----------------------------------------------------------------------

I've done some debugging, and while the 'level' tensor appears correct, the 'verts' and 'faces' are empty. It seems there might be a problem with the mc_func. I've tried both torchcubes and mcubes. When running the code with torchcubes, I get values for 'verts' but 'faces' remains empty. With mcubes, both 'verts' and 'faces' are empty.

I haven't altered any other part of your code, and my input is a series of frames from a small room shot at 1920x1080.

If you could provide any insight or solution to this issue, I would greatly appreciate it.

Thank you.

**Comment by hugoycj** [comment]
![download](https://github.com/hugoycj/Instant-angelo/assets/40767265/b4ac0fad-d25f-482e-be71-9e432032325d)
Sorry to bother you,  the current process only reconstructs the center cube like this, which presents difficulties when attempting to reconstruct a room or when the camera poses are situated on the same plane. 

One possible solution could be enlarge the `model.radius` in the config, while some other parameters like `start_level` and `final_level` for ProgressiveBandHashGrid need to be substantially increased.

I am planning to address and resolve it by submitting a pull request later this month. Thank you for your understanding and patience.

**Comment by vietpho** [comment]
Thank you for the update. I appreciate the effort you're putting into resolving this issue.
