### ISSUE TITLE
pairs.txt missing in Dense pipeline

### ISSUE THREAD

**Issue by cdcseacave** [hugoycj/Instant-angelo#42]
I'm trying to test using this command:
```
bash run_neuralangelo-colmap_dense.sh ~/data/truck
```
but I get this error:
```
---colmap2mvsnet---
Traceback (most recent call last):
  File "/home/ubuntu/Instant-angelo/third_party/Vis-MVSNet/colmap2mvsnet.py", line 354, in <module>
    zs.append(np.asscalar(transformed[2]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/numpy/__init__.py", line 328, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'. Did you mean: 'isscalar'?
Traceback (most recent call last):
  File "/home/ubuntu/Instant-angelo/third_party/Vis-MVSNet/test.py", line 63, in <module>
    dataset, loader = get_val_loader(
  File "/home/ubuntu/Instant-angelo/third_party/Vis-MVSNet/data/general.py", line 78, in get_val_loader
    dataset = MyDataset(
  File "/home/ubuntu/Instant-angelo/third_party/Vis-MVSNet/data/general.py", line 19, in __init__
    self.pair = load_pair(os.path.join(self.root, f'pair.txt'))
  File "/home/ubuntu/Instant-angelo/third_party/Vis-MVSNet/utils/io_utils.py", line 13, in load_pair
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/truck/dense/pair.txt'
```
It is used in several places, but nobody generates that file. From where should I get it?

**Comment by xsl316** [comment]
pairs.txt is generated when calling the colmap2mvsnet.py file
